version: '3.9'
services:
  bot:
    image: thetipo01/videodownloader
    restart: always
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro