# Telegram bot token
token:

# URLs of the video hosting services to download from
urls:
  - instagram.com
  - tiktok.com
  - youtube.com/shorts
  - fb.watch
  - reddit.com

# A group or channel to send video to
# Needed as telegram bots can't send file directly when using inline mode
channel:

# Log level
loglevel: informational

# TikTok downloader,
# see https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/README.en.md#deployment-method-1-linux
# for more information on how to deploy it
downloader: "http://localhost:8080"