# Telegram bot token
token:

# URLs of the video hosting services to download from
urls:
  - instagram.com
  - tiktok.com
  - youtube.com/shorts
  - fb.watch
  - reddit.com

# A group or channel to send video to
# Needed as telegram bots can't send file directly when using inline mode
channel:

# Log level
loglevel: informational