# Telegram bot token
token:

# URLs of the video hosting services to download from
urls:
  - instagram.com
  - tiktok.com
  - youtube.com/shorts
  - fb.watch
  - reddit.com

# Log level
loglevel: informational